[package]
name = "dynasty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance-rs-async = { version = "1.3.1", features = ["wallet_api"] }
chrono = "0.4.24"
futures = "0.3.28"
iced = { version = "0.10.0", features = ["tokio", "debug"] }
iced_futures = "0.7.0"
iced_native = "0.10.3"
itertools = "0.11.0"
lazy_static = "1.4.0"
once_cell = "1.17.1"

[dependencies.async-tungstenite]
version = "0.23"
features = ["tokio-rustls-webpki-roots"]

[dependencies.tokio]
version = "1"
features = ["time"]

[dependencies.warp]
version = "0.3"
